export const colorSetting = [
  { value: "#b3b2b2", label: "Galvalume" },
  { value: "#CFCFDC", label: "Polar White" },
  { value: "#100F0F", label: "Black" },
  { value: "#ACA0A0", label: "Ash Gray" },
  { value: "#777570", label: "Slate Gray" },
  { value: "#605B5D", label: "Charcoal Gray" },
  { value: "#504541", label: "Burnished Slate" },
  { value: "#4F3936", label: "Brown" },
  { value: "#B59380", label: "Coffee Tan" },
  { value: "#A3927D", label: "Stone Tan" },
  { value: "#9F9181", label: "Tan" },
  { value: "#D0C6B4", label: "Almond" },
  { value: "#C8B6AA", label: "Light Stone" },
  { value: "#534940", label: "Medium Bronze" },
  { value: "#3E3A38", label: "Dark Bronze" },
  { value: "#314A40", label: "Evergreen" },
  { value: "#2F483B", label: "Green" },
  { value: "#486C83", label: "Hawaiian Blue" },
  { value: "#1C4B60", label: "Harbor Blue" },
  { value: "#863E39", label: "Barn Red" },
  { value: "#A02223", label: "Red" },
  { value: "#AE7550", label: "Painted Copper" },
];
