export const sidebarData = [
  {
    title: "Choose your style",
    titleDb: "chooseyourstyle",
    inputType: "select",
    objectValue: [
      {
        id: "style",
        name: "Style",
        value: ["Gable", "Single Slope"],
      },
    ],
  },

  {
    title: "Choose your size",
    titleDb: "chooseyoursize",
    type: "size",
    inputType: "select",

    objectValue: [
      {
        id: "width",
        name: "Width",
        value: ["20-40", "41-60", "61-80"],
      },
      {
        id: "eaveheight",
        name: "Eave Height",
        value: [
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
        ],
      },
      {
        id: "roofpitch",
        name: "Roof Pitch",
        value: [
          { value: "1:12", label: "1/12" },
          { value: "2:12", label: "2/12" },
          { value: "3:12", label: "3/12" },
          { value: "4:12", label: "4/12" },
          { value: "5:12", label: "5/12" },
          { value: "6:12", label: "6/12" },
          { value: "7:12", label: "7/12" },
          { value: "8:12", label: "8/12" },
        ],
      },

      {
        id: "insetbaylength",
        name: "Inset Bay Length",
        value: [
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
          "34",
          "35",
          "36",
          "37",
          "38",
          "39",
          "40",
        ],
      },
      {
        id: "roofonly",
        name: "Roof Only",
        value: "Select to remove all walls",
      },
    ],
  },

  // {
  //   title: "Add Lean-to",
  //   titleDb: "addleanto",
  //   type: "attachments",
  //   extraFiled: "Size",
  //   inputType: "select",
  //   multipleSelect: true,
  //   inputWithClick: true,
  //   objectValue: [
  //     {
  //       id: "closure",
  //       name: "Closure",
  //       value: ["Open", "Enclosed"],
  //     },
  //     {
  //       id: "width",
  //       name: "Width",
  //       value: [
  //         "8",
  //         "9",
  //         "10",
  //         "11",
  //         "12",
  //         "13",
  //         "14",
  //         "15",
  //         "16",
  //         "17",
  //         "18",
  //         "19",
  //         "20",
  //         "21",
  //         "22",
  //         "23",
  //         "24",
  //         "25",
  //       ],
  //     },
  //     {
  //       id: "length",
  //       name: "Length",
  //       value: ["20", "40", "60"],
  //     },
  //     {
  //       id: "dropheight",
  //       name: "Drop Height",
  //       value: ["1", "2", "3", "4", "5", "6", "7", "8"],
  //     },

  //     {
  //       id: "roofpitch",
  //       name: "Roof Pitch",
  //       value: ["1:12", "2:12", "3:12", "4:12"],
  //     },
  //   ],
  // },

  {
    title: "Add Overhang",
    titleDb: "addoverhang",
    type: "addoverhang",
    objectValue: [
      {
        id: "eaveoverhang",
        name: "Eave Overhang",
        value: ["1", "2", "3", "4", "5", "6"],
      },
      {
        id: "gableoverhang",
        name: "Gable Overhang",
        value: ["1", "2", "3", "4", "5", "6"],
      },
    ],
  },

  {
    title: "Choose your window and door openings",
    titleDb: "choosewindowdoor",
    inputType: "select",
    type: "doorswindows",

    objectValue: [
      {
        id: "walkdoor",
        name: "Walk-door",
        value: ["3 x 7", "4 x 7", "6 x 7"],
      },
      {
        id: "rollupdoor",
        name: "Roll-up door",
        value: [
          "8 x 8",
          "8 x 10",
          "10 x 8",
          "10 x 10",
          "10 x 12",
          "10 x 14",
          "12 x 8",
          "12 x 10",
          "12 x 12",
          "12 x 14",
          "14 x 8",
          "14 x 10",
          "14 x 12",
          "14 x 14",
        ],
      },
      {
        id: "window",
        name: "Window",
        value: [
          "3 x 3",
          "3 x 4",
          "3 x 5",
          "4 x 3",
          "4 x 4",
          "4 x 5",
          "6 x 3",
          "6 x 4",
          "6 x 5",
        ],
      },
    ],
  },
  // {
  //   title: "Add interior liner panels",
  //   inputType: "click",
  //   titleDb: "interiorlinerpanels",
  //   objectValue: [
  //     {
  //       id: "linerpanels",
  //       name: "Liner panels",
  //       value: "8’ interior liner panel on all perimeter walls",
  //     },
  //   ],
  // },
  {
    title: "Optional upgrades",
    titleDb: "optionalupgrades",
    inputType: "click",

    objectValue: [
      {
        id: "wainscot",
        name: "Wainscot",
        value: "Select to add 3' wainscot",
      },

      {
        id: "eaveheight",
        name: "Eave Height",
        value: [
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
        ],
      },
    ],
  },
];
